image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name bts-nfcreader --icon icon.png --product-name bts-nfcreader --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2022

  after_build:
  - 7z a bts-nfcreader-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: bts-nfcreader-windows.zip

#
#   macOS package
# 
# -
#   matrix:
#     only:
#     - image: macOS

#   after_build:
#   - tar -czvf bts-nfcreader-macos.tar.gz -C dist bts-nfcreader.app

#   artifacts:
#   - path: bts-nfcreader-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu
  
  before_build:
  - sudo apt install libpcsclite
  
  after_build:
  - tar -czvf bts-nfcreader-linux.tar.gz -C dist bts-nfcreader

  artifacts:
  - path: bts-nfcreader-linux.tar.gz
  